### PR TITLE
Add headerAlignment for content

### PR DESCRIPTION
**Pull request by AndriiZakhliupanyi**
Hi!

I need alignment for header content.
For example: For my content remained attached to the top.

I added headerAlignment.

### CODE REVIEW

**Comment by AndriiZakhliupanyi** [comment]
Can someone review PR?

**Comment by f3dm76** [comment]
Hey @AndriiZakhliupanyi, thank you for your contribution, have a wonderful day!

**Comment by AndriiZakhliupanyi** [comment]
@f3dm76 can you update podfile to 0.1.6?

**Comment by f3dm76** [comment]
@AndriiZakhliupanyi done, but you can always use master branch

**Comment by AndriiZakhliupanyi** [comment]
@f3dm76  thanks

**Pull request merged**
