### PR TITLE
Bump swiftui-introspect to 1.3.0 to fix iOS 18 support

### PR DESCRIPTION
**Pull request by dwnz**
Had a few issues getting this to work nicely on iOS 18 - installed the latest package and ran into this issue #62 

Have updated my project to use my fork and tested in iOS 18, seems to all work now. Not sure if/how you normally accept PRs but I hope this helps

### CODE REVIEW

**Comment by f3dm76** [comment]
Thank you for your contribution, @dwnz, have a great day!

**Comment by dwnz** [comment]
No worries @f3dm76! Glad I could help

**Comment by jeffphp** [comment]
> Thank you for your contribution, @dwnz, have a great day!

Thanks for merging this fix. Could you please release a version integrating the fix?

Best regards

**Comment by f3dm76** [comment]
Hey @jeffphp, done, best regards

**Pull request merged**
