### PR TITLE
add scrollOffset for binding

### PR DESCRIPTION
**Pull request by AndriiZakhliupanyi**
Hi!

I need get current scroll offset in parent View.

I added binding for it.

Have a nice day!

### CODE REVIEW

**Comment by f3dm76** [comment]
Hey @AndriiZakhliupanyi thank you for your work! Have a wonderful day!

**Comment by AndriiZakhliupanyi** [comment]
Thanks for the quick review!

When will you update to 0.1.4?

**Comment by f3dm76** [comment]
Done

**Comment by AndriiZakhliupanyi** [comment]
Thanks!

**Pull request merged**
