### PR TITLE
Issue-16

### PR DESCRIPTION
**Pull request by svetzhelev**
Bugfix for error message 'Modifying state during view update, this will cause undefined behavior'.

### CODE REVIEW

**Comment by f3dm76** [comment]
Hey @svetzhelevm, thank you or your work. However, are you sure this fix won't change the behaviour? `configure` function not only sets `uiScrollView`'s value but also sets up some callbacks. Could you please see if there's a way to narrow down the cause of the error message and only limit that, not the whole `configure` call? Or I can see to that once I have time

**Comment by svetzhelev** [comment]
> Hey @svetzhelevm, thank you for your work. However, are you sure this fix won't change the behaviour? `configure` function not only sets `uiScrollView`'s value but also sets up some callbacks. Could you please see if there's a way to narrow down the cause of the error message and only limit that, not the whole `configure` call? Or I can see to that once I have time

I do not think it will as you only set the scrollview once and configure it once per instance. Or I am wrong?

**Comment by ahbou** [comment]
Can someone approve this fix please? I see this run time error all the time.

**Comment by f3dm76** [comment]
@ahbou Please check out version 0.1.0, should be fixed there, have a great day!

**Pull request closed without merging**
